### ISSUE TITLE
Allow clients to communicate read/seen status to each other

### ISSUE THREAD

**Issue by torarnv** [ircv3/ircv3-ideas#1]
It would be nice if there was a way for clients to communicate to other clients that a message has been read/seen. This has two use-cases:
1. In a bouncer setup with multiple clients per user, it can be used to sync the scrollback marker/unread count between the user's clients.
2. It can be used to (optionally) inform other users that a message has been read/seen, similar to how Facebook Messenger conversations [work](https://www.facebook.com/help/messenger-app/926389207386625). This use-case would typically be configurable on the client, to let the user decide whether or not to send these notifications, possibly only to a subset of users (known contacts), and in response to which action, eg. focusing the buffer of the conversation.

Prior art for the first use-case is e.g. Slack's [`im_marked`](https://api.slack.com/events/im_marked) notification, and for the second use-case, Facebook Messenger's [`message_reads`](https://developers.facebook.com/docs/messenger-platform/webhook-reference/message-read) callback.

Both protocols use a simple timestamp to signify the read-cursor/watermark.

A prototype of the first use-case has been implemented as the `znc.in/message-seen` capability, available as a [ZNC module](http://wiki.znc.in/Messageseen), with support in the [Communi](https://github.com/communi/communi-desktop/pull/112) desktop client.

**Comment by jwheare** [comment]
Can you describe how `znc.in/message-seen` works at the moment?

**Comment by torarnv** [comment]
At the moment it's a simple `MSGSEEN target timestamp` command, sent from the client when the buffer receives a message and has focus, or focus is changed to a buffer that has unseen messages (this behavior can of course be configured on a per client basis). 

The timestamp is the server time of the message, so this capability requires `server-time`.

The ZNC `messageseen` module simply echoes this command back to the other clients connected for that user, with the user's prefix.

The other clients then receive `:prefix MSGSEEN target timestamp`, and if prefix matches their own user will update the timestamp of the target buffer. Updating the timestamp then propagates to recomputing unread message counts and the scrollback marker, but this is up to each client.

For use-case two, the prefix could be another user, in which case the client could signal that the other user has read the outgoing message up until a certain point, or show e.g. "_5 of 14 users have read your message_" - again up to the client.

**Comment by jwheare** [comment]
The timestamp form works well for multiple users of a bouncer, but for other clients, this relies on server-supplied message ids. Bundling this issue into the grab bag of similar issues in ircv3/ircv3-specifications#246.

**Comment by jwheare** [comment]
Closing in favour of ircv3/ircv3-specifications#319
