### ISSUE TITLE
Add an optional context parameter to the first AUTHENTICATE message.

### ISSUE THREAD

**Issue by sadiepowell** [ircv3/ircv3-ideas#20]
On IRC there are multiple things that someone might want to log into. Due to security needs it is not always desirable to use the same credentials for all of these things so separate logins are required.

I propose that this is fixed by adding an optional context parameter to the initial AUTHENTICATE message like so:

```
initial-authenticate = "AUTHENTICATE" SP mechanism [ SP context ] CRLF
```

Two new contexts in which this would be useful:

1. `server` -- logging in to the server as an alternative to `PASS`.
2. `operator` -- logging into operator accounts (which are separate from services accounts) as an alternative to `OPER`.

If no context parameter is provided we can default it to `account` which would be the existing SASL behaviour. This would preserve existing behaviour for legacy implementations because as far as I know existing implementations extraneous parameters to the AUTHENTICATE command just like with CAP (which allowed us to enable cap-3.2 with a value of 302).

**Comment by DarthGandalf** [comment]
Another idea for the second parameter: the first message for client-first mechanisms, without need to wait until server sends `AUTHENTICATE +`

**Comment by jwheare** [comment]
Re: the original idea. Makes sense and I just confirmed it's backwards-compatible with atheme >=7.2.5
