### ISSUE TITLE
Discuss considerations to keep in mind while implementing +draft/typing

### ISSUE THREAD

**Issue by jesopo** [ircv3/ircv3-ideas#42]
Making this issue primarily to collect ideas.

KiwiIRC and Snoonet are currently in-the-wild showing typing status and I saw some backlash over it. Probably best we discuss the potentially unforeseen impact of this spec, what we think about it, what we think (if anything) could/should be done about it, etc.

**Comment by prawnsalad** [comment]
Quick note, Snoonet does not yet support message-tags which is needed for the typing draft. It's irc.irc.com:+6697 or any network that runs the latest webircgateway for their web clients.

**Comment by DanielOaks** [comment]
Should be noted, this thread's more about collecting potential implementation considerations on the typing spec. I mean we foresaw all sorts of _potential_ things (including most of what's been mentioned), now that implementations are happening in the wild it's a good time to note these considerations down so future implementers have them already.

**Comment by jwheare** [comment]
Already covered in the spec no?

https://ircv3.net/specs/client-tags/typing.html#privacy-considerations

> Typing status indicators introduce additional privacy concerns for users who may not wish to inform others of when they are creating or replying to a message. Clients are encouraged to provide appropriate privacy controls when enabling this feature.

**Comment by jwheare** [comment]
Unless there are other concerns that haven't actually been mentioned in this issue...

**Comment by jesopo** [comment]
The criticisms I observed were along the lines of

- "I'd use discord if I wanted typing indicators"
- "this is very much not what IRC is about"
- "typing indicators are anxiety-inducing"
- "this is an information leak that I was not aware I was partaking in"

I don't really agree to the first two but I'm definitely on-board with the last two. Maybe the crux of the issue in the instance I observed was that it's opt-out, not opt-in. I'm not sure if I agree with it being opt-out and I agree the wording is already fairly good for it.

Maybe "disabling sending typing status also disables showing the typing status of other people" could be enough for this - maybe asking some big players to make it more obvious that it is happening could work but surely when people see other people's typing status, they'll realise they're probably sending it too. I don't know.

**Comment by jwheare** [comment]
The decision on whether to opt-out or opt-in will likely depend on individual client's userbase. How they choose to expose that setting is out of scope, and whether they want to have a toggle for hiding the ui element even for other people is also arguably out of scope. I think it's the sort of thing that gets decided based on feedback between client devs and their users.

**Comment by jwheare** [comment]
I think this is resolved, if not please shout and we can reopen.
