### ISSUE TITLE
Standardise NOTICE within channel context

### ISSUE THREAD

**Issue by jesopo** [ircv3/ircv3-ideas#44]
Simple premise - imagine a bot that greets users via `NOTICE` when they join a channel. This is currently often done by `NOTICE user :[#channel] hello!` but I think we could do something a lot better than that.

My proposition: `@+channel-context=#channel NOTICE user :[#channel] hello!` - it'd be backwards compatible and be a lot more concretely related to a channel.

**Comment by DanielOaks** [comment]
This sort of tag sounds reasonable but the `"[#channel] "` on the front of the message feels not-that-needed. Most of the time, if users join a channel and instantly get a message from a bot they're gonna recognise it (and most other channel-specific bot dms are gonna happen in response to commands they actively run, so no worries about them noticing what it's from).

**Comment by grawity** [comment]
The prefix is useful as the client can use it as a hint for choosing the window (e.g. WeeChat shows such notices as PvNotice in the channel window, like a whisper). Without it, clients either dump notices in the server window (where they can get lost) or in the foreground window (which can be the wrong channel entirely).

I realize that ctctags are more suitable but the prefix is in active use now, e.g. by Atheme's Chanserv and the aforementioned WeeChat.

**Comment by DanielOaks** [comment]
Mm. Yeah thinking about it sounds fine, esp as something that works right now everywhere.

**Comment by DanielOaks** [comment]
It seems this prolly already exists out there by way of cnotice/cprivmsg, if we can just use this then cool: https://tools.ietf.org/html/draft-hardy-irc-isupport-00#section-4.6

**Comment by jesopo** [comment]
that would prohibit non-op bots from using it and it seems to not include a channel context - just allows an op to message the user without flood controls.

**Comment by DanielOaks** [comment]
ah, I missed the bit about that being restricted to ops/etc. if that's true then that too, bleh. fairfair

**Comment by grawity** [comment]
> It seems this prolly already exists out there by way of cnotice/cprivmsg, if we can just use this then cool: https://tools.ietf.org/html/draft-hardy-irc-isupport-00#section-4.6

In addition to the op-only restrictions, CNOTICE isn't actually channel-scoped -- it still generates a standard private NOTICE, it only allows the common channel to be used as an excuse for bypassing antiflood limits and such.

**Comment by emersion** [comment]
Alternatively, this could be a server tag, and the server could add the prefix if the client doesn't support the extension.

**Comment by jesopo** [comment]
on review of this, I think I'd prefer this be moved to a numeric instead of a `NOTICE`. I don't know if clients are good at redirecting unknown notices to channel buffers though.

**Comment by emersion** [comment]
This has been standardized with https://github.com/ircv3/ircv3-specifications/pull/498
