### ISSUE TITLE
Allow spaces in NETWORK ISUPPORT

### ISSUE THREAD

**Issue by emersion** [ircv3/ircv3-ideas#81]
The `NETWORK` `ISUPPORT` token allows servers to advertise their name. However spaces aren't allowed, sometimes this forces servers to pick an awkward name (e.g. with CamelCase or hyphens).

It would be nice to allow using `\s` to include spaces in the `NETWORK` (same escaping as message tags).

**Comment by jesopo** [comment]
`ISUPPORT` already supports hex escapes. use `\x20` for this

**Comment by emersion** [comment]
Oh, nice, didn't know. Is there a reference on this? I didn't find it in modern.ircdocs.horse.

**Comment by jesopo** [comment]
https://datatracker.ietf.org/doc/html/draft-brocklesby-irc-isupport-03 ctrl+f `\x`

**Comment by emersion** [comment]
Thanks!

https://datatracker.ietf.org/doc/html/draft-brocklesby-irc-isupport-03#page-5

**Comment by emersion** [comment]
Also ref https://github.com/ircdocs/modern-irc/pull/137
