### ISSUE TITLE
+monospace tag

### ISSUE THREAD

**Issue by awfulcooking** [ircv3/ircv3-ideas#93]
Many users, including me, prefer to read conversations in variable-width. It lets me read faster and fit more text on the screen.

But I still like to enjoy ASCII / Unicode art, and text such as bot replies which have been carefully formatted for fixed-width.

A +monospace tag, or similar, would help with this.

**Comment by dgw** [comment]
I take it the advantage of this over the existing monospace control code is that it would work even in channels that block messages containing formatting?

The bot(s) must to be modified either way, to send the new tag or to include the control code. Difference is, this feature doesn't exist yet, but the control code can be used _today_ in a number of clients that already handle it.

**Comment by awfulcooking** [comment]
Oh. it's solved, then.

Maybe there are some client / bot devs who weren't aware of this either. And if you want to support it, well, the more the merrier 🙂
